from __future__ import annotations

import time
from typing import TypedDict, Annotated, Literal
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, END
from langchain_litellm import ChatLiteLLM
from langchain_core.messages import BaseMessage, AIMessage

from agent_harness_cookbook.harness.audit import AuditStore

class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]

# 1. Harness integration
store = AuditStore()
llm = ChatLiteLLM(model="gpt-4o-mini")

# 2. Nodes
def call_model(state: AgentState):
    response = AIMessage(content="I reasoned about the state.")
    
    # WRAPPER: Log the exact message generated by the LLM
    store.record(
        event_type="llm_generation",
        actor="langgraph-agent",
        payload={"content": response.content}
    )
    
    return {"messages": [response]}

# 3. Build Graph
builder = StateGraph(AgentState)
builder.add_node("agent", call_model)

builder.set_entry_point("agent")
builder.add_edge("agent", END)

graph = builder.compile()

def run_example():
    print("--- Pattern 03: Enterprise LangGraph Decision Trace & Audit ---\\n")
    graph.invoke({"messages": [("user", "Start")]})
    print("Events logged:", [e["event_type"] for e in store.as_dicts()])

if __name__ == "__main__":
    run_example()
